import {spawn} from "node:child_process";
import {promises as fs} from "node:fs";
import path from "node:path";
import {ExecutionTraceSchema, type ExecutionTrace, type Snapshot, type ViewSpec} from "../src/algorithm-video/schema";
import {traceRoots} from "../src/algorithm-video/trace-roots";
import {visibleCandidatesByLine} from "./cpp-scope";
import type {TraceRequest, Tracer} from "./tracer";
type RawRecord = {line: number; function: string; variables: Snapshot};
const runCapture = (command: string, args: string[], options: {cwd: string; input?: string; timeoutMs: number}) => new Promise<{stdout: string; stderr: string; exitCode: number}>((resolve, reject) => { const child = spawn(command, args, {cwd: options.cwd, stdio: ["pipe", "pipe", "pipe"]}); let stdout = ""; let stderr = ""; child.stdout.on("data", (chunk) => {stdout += String(chunk);}); child.stderr.on("data", (chunk) => {stderr += String(chunk);}); child.stdin.end(options.input ?? ""); const timer = setTimeout(() => {child.kill("SIGKILL"); reject(new Error(`${command} vượt timeout ${options.timeoutMs}ms.`));}, options.timeoutMs); child.on("error", (error) => {clearTimeout(timer); reject(error);}); child.on("exit", (code) => {clearTimeout(timer); resolve({stdout, stderr, exitCode: code ?? -1});}); });
const emitCall = (line: number, variables: string[], prefix: string) => `${prefix}algorithm_trace::emit(${line}, __func__${variables.map((name) => `, algorithm_trace::named("${name}", ${name})`).join("")});`;
const instrument = (source: string, view: ViewSpec) => { const lines = source.split(/\r?\n/); const candidates = traceRoots(view); const visibleByLine = visibleCandidatesByLine(source, candidates); const result: string[] = ['#include "trace_runtime.hpp"']; for (let index = 0; index < lines.length; index++) { const lineNo = index + 1; const line = lines[index]; const trimmed = line.trim(); const indent = line.match(/^\s*/)?.[0] ?? ""; const inRange = lineNo >= view.show.startLine && lineNo <= view.show.endLine; const available = visibleByLine.get(lineNo) ?? []; if (!inRange || !trimmed || trimmed.startsWith("//") || trimmed.startsWith("#")) { result.push(line); continue; } const control = /^(for|while)\s*\(/.test(trimmed); const conditional = /^if\s*\(/.test(trimmed); if ((control || conditional) && !trimmed.includes("{")) throw new Error(`Dòng ${lineNo}: control statement cần dùng { } để ghi trace mà không đổi ngữ nghĩa.`); if (conditional) result.push(emitCall(lineNo, available, indent)); if (/^return\b/.test(trimmed)) result.push(emitCall(lineNo, available, indent)); result.push(line); if (control && trimmed.includes("{")) result.push(emitCall(lineNo, available, `${indent}  `)); else if (!conditional && trimmed.endsWith(";") && !/^(return|break|continue|throw)\b/.test(trimmed)) result.push(emitCall(lineNo, available, indent)); } return `${result.join("\n")}\n`; };
export class InstrumentedTracer implements Tracer {
  async trace(request: TraceRequest): Promise<ExecutionTrace> {
    if (!request.view) throw new Error("InstrumentedTracer cần view spec."); const timeoutMs = request.timeoutMs ?? 30_000; const maxSteps = request.maxSteps ?? 5000;
    const sourceCopy = path.join(request.jobDirectory, path.basename(request.sourcePath)); const inputCopy = path.join(request.jobDirectory, "input.txt"); const instrumentedPath = path.join(request.jobDirectory, "instrumented.cpp"); const runtimePath = path.join(request.jobDirectory, "trace_runtime.hpp"); const binaryPath = path.join(request.jobDirectory, "program"); const rawPath = path.join(request.jobDirectory, "trace.raw.jsonl"); const tracePath = path.join(request.jobDirectory, "trace.json"); const source = await fs.readFile(request.sourcePath, "utf8");
    await Promise.all([fs.copyFile(request.sourcePath, sourceCopy), fs.copyFile(request.inputPath, inputCopy), fs.copyFile(path.resolve("scripts/trace_runtime.hpp"), runtimePath), fs.writeFile(instrumentedPath, instrument(source, request.view)), fs.rm(rawPath, {force: true})]);
    const compiled = await runCapture("/usr/bin/clang++", ["-std=c++17", "-g", "-O0", instrumentedPath, "-o", binaryPath], {cwd: request.jobDirectory, timeoutMs}); if (compiled.exitCode !== 0) throw new Error(`Không thể biên dịch bản ghi vết:\n${compiled.stderr}`);
    const executed = await runCapture(binaryPath, [], {cwd: request.jobDirectory, input: await fs.readFile(inputCopy, "utf8"), timeoutMs}); const raw = (await fs.readFile(rawPath, "utf8")).trim().split("\n").filter(Boolean).map((line) => JSON.parse(line) as RawRecord); const truncated = raw.length > maxSteps; const records = raw.slice(0, maxSteps); let previous: Snapshot | null = null;
    const steps = records.map((record, index) => { const before = previous ?? record.variables; previous = record.variables; return {index, line: record.line, displayLine: Math.max(request.showStart, Math.min(request.showEnd, record.line)), function: record.function, depth: 0, before, after: record.variables}; }); const payload = ExecutionTraceSchema.parse({version: 1, sourceFile: path.basename(request.sourcePath), stdout: executed.stdout, exitCode: executed.exitCode, truncated, steps}); const encoded = `${JSON.stringify(payload, null, 2)}\n`; if (Buffer.byteLength(encoded) > (request.maxTraceBytes ?? 8_000_000)) throw new Error("Trace vượt giới hạn kích thước."); await Promise.all([fs.writeFile(tracePath, encoded), fs.writeFile(path.join(request.jobDirectory, "program.stdout.txt"), executed.stdout), fs.writeFile(path.join(request.jobDirectory, "program.stderr.txt"), executed.stderr)]); return payload;
  }
}
